---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
      name: virtualbox
platforms:
  - name: moleculeinstance
    box: generic/ubuntu2004
    memory: 521
    cpus: 1
provisioner:
  name: ansible
verifier:
  name: ansible
